GET http://localhost:3001/api/users
###

POST http://localhost:3001/api/book
Content-Type: application/json

{
     "title":"book 15", "year": 2015, "rating": 3
}

###
GET http://localhost:3001/api/book
###
#### get single book
GET http://localhost:3001/api/book/62605176a79950379ea93370

###
#### delete single book
DELETE http://localhost:3001/api/book/626056c9a2bb49c5fed769d5

###

POST http://localhost:3001/api/author
Content-Type: application/json

{
    "name":"Jannet book3", "town": "Vilnius", "bookId": "625f507ce069d761556af22c" 
}
###
GET http://localhost:3001/api/author
###
GET http://localhost:3001/api/book-authors
###
GET http://localhost:3001/api/book-agg2
###

